---
name: Validate

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache
        uses: nmerget/npm-cache-action@main

      - name: 🔬 Validate repo
        run: npm run lint
